#!/bin/sh

TARGET=$MSYSTEM_CARCH
#PACMAN_EXTRA_ARGS="--noprogressbar"

pacman -S --noconfirm --needed $PACMAN_EXTRA_ARGS \
	unzip                          \
	curl                           \
	make                           \
	msys/perl-common-sense         \
	mingw-w64-${TARGET}-gcc        \
	mingw-w64-${TARGET}-nsis       \
	mingw-w64-${TARGET}-qt5        \
	mingw-w64-${TARGET}-gdal       \
	mingw-w64-${TARGET}-proj       \
	mingw-w64-${TARGET}-openjpeg2  \
	mingw-w64-${TARGET}-json-c     \
	mingw-w64-${TARGET}-netcdf     \
	mingw-w64-${TARGET}-nspr       \
	mingw-w64-${TARGET}-nss        \
	mingw-w64-${TARGET}-postgresql

# netcdf, nspr, nss and postgres are not direct dependencies, but are linked
# from others (and are not correctly entered in the msys packages)
