#ifndef _PROJECTIONS_CEA_HPP
#define _PROJECTIONS_CEA_HPP

// Generic Geometry Library - projections (based on PROJ4)
// This file is automatically generated. DO NOT EDIT.

// Copyright Barend Gehrels (1995-2009), Geodan Holding B.V. Amsterdam, the Netherlands.
// Copyright Bruno Lalande (2008-2009)
// Use, modification and distribution is subject to the Boost Software License,
// Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

// This file is converted from PROJ4, http://trac.osgeo.org/proj
// PROJ4 is originally written by Gerald Evenden (then of the USGS)
// PROJ4 is maintained by Frank Warmerdam
// PROJ4 is converted to Geometry Library by Barend Gehrels (Geodan, Amsterdam)

// Original copyright notice:

// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include <geometry/projections/impl/base_static.hpp>
#include <geometry/projections/impl/base_dynamic.hpp>
#include <geometry/projections/impl/projects.hpp>
#include <geometry/projections/impl/factory_entry.hpp>
#include <geometry/projections/impl/pj_qsfn.hpp>
#include <geometry/projections/impl/pj_auth.hpp>

namespace projection
{
	#ifndef DOXYGEN_NO_IMPL
	namespace impl
	{
		namespace cea
		{
			static const double EPS = 1e-10;

			struct par_cea
			{
				double qp;
				double apa[APA_SIZE];
			};

			// template class, using CRTP to implement forward/inverse
			template <typename LL, typename XY, typename PAR>
			struct base_cea_ellipsoid : public base_t_fi<base_cea_ellipsoid<LL, XY, PAR>, LL, XY, PAR>
			{

				typedef typename base_t_fi<base_cea_ellipsoid<LL, XY, PAR>, LL, XY, PAR>::LL_T LL_T;
				typedef typename base_t_fi<base_cea_ellipsoid<LL, XY, PAR>, LL, XY, PAR>::XY_T XY_T;

				par_cea m_proj_parm;

				inline base_cea_ellipsoid(const PAR& par)
					: base_t_fi<base_cea_ellipsoid<LL, XY, PAR>, LL, XY, PAR>(*this, par) {}

				inline void fwd(LL_T& lp_lon, LL_T& lp_lat, XY_T& xy_x, XY_T& xy_y) const
				{
					xy_x = this->m_par.k0 * lp_lon;
					xy_y = .5 * pj_qsfn(sin(lp_lat), this->m_par.e, this->m_par.one_es) / this->m_par.k0;
				}

				inline void inv(XY_T& xy_x, XY_T& xy_y, LL_T& lp_lon, LL_T& lp_lat) const
				{
					lp_lat = pj_authlat(asin( 2. * xy_y * this->m_par.k0 / this->m_proj_parm.qp), this->m_proj_parm.apa);
					lp_lon = xy_x / this->m_par.k0;
				}
			};

			// template class, using CRTP to implement forward/inverse
			template <typename LL, typename XY, typename PAR>
			struct base_cea_spheroid : public base_t_fi<base_cea_spheroid<LL, XY, PAR>, LL, XY, PAR>
			{

				typedef typename base_t_fi<base_cea_spheroid<LL, XY, PAR>, LL, XY, PAR>::LL_T LL_T;
				typedef typename base_t_fi<base_cea_spheroid<LL, XY, PAR>, LL, XY, PAR>::XY_T XY_T;

				par_cea m_proj_parm;

				inline base_cea_spheroid(const PAR& par)
					: base_t_fi<base_cea_spheroid<LL, XY, PAR>, LL, XY, PAR>(*this, par) {}

				inline void fwd(LL_T& lp_lon, LL_T& lp_lat, XY_T& xy_x, XY_T& xy_y) const
				{
					xy_x = this->m_par.k0 * lp_lon;
					xy_y = sin(lp_lat) / this->m_par.k0;
				}

				inline void inv(XY_T& xy_x, XY_T& xy_y, LL_T& lp_lon, LL_T& lp_lat) const
				{
					double t;

					if ((t = fabs(xy_y *= this->m_par.k0)) - EPS <= 1.) {
						if (t >= 1.)
							lp_lat = xy_y < 0. ? -HALFPI : HALFPI;
						else
							lp_lat = asin(xy_y);
						lp_lon = xy_x / this->m_par.k0;
					} else throw proj_exception();;
				}
			};

			// Equal Area Cylindrical
			template <typename PAR>
			void setup_cea(PAR& par, par_cea& proj_parm)
			{
				double t;
				if (pj_param(par.params, "tlat_ts").i &&
					(par.k0 = cos(t = pj_param(par.params, "rlat_ts").f)) < 0.) throw proj_exception(-24);
				else
					t = 0.;
				if (par.es) {
					t = sin(t);
					par.k0 /= sqrt(1. - par.es * t * t);
					par.e = sqrt(par.es);
					pj_authset(par.es, proj_parm.apa);
					proj_parm.qp = pj_qsfn(1., par.e, par.one_es);
				// par.inv = e_inverse;
				// par.fwd = e_forward;
				} else {
				// par.inv = s_inverse;
				// par.fwd = s_forward;
				}
			}

		} // namespace cea
	} //namespaces impl
	#endif // doxygen

	/*!
		\brief Equal Area Cylindrical projection
		\ingroup projections
		\tparam LL latlong point type
		\tparam XY xy point type
		\tparam PAR parameter type
		\par Projection characteristics
		 - Cylindrical
		 - Spheroid
		 - Ellipsoid
		 - lat_ts=
		\par Example
		\image html ex_cea.gif
	*/
	template <typename LL, typename XY, typename PAR = parameters>
	struct cea_ellipsoid : public impl::cea::base_cea_ellipsoid<LL, XY, PAR>
	{
		inline cea_ellipsoid(const PAR& par) : impl::cea::base_cea_ellipsoid<LL, XY, PAR>(par)
		{
			impl::cea::setup_cea(this->m_par, this->m_proj_parm);
		}
	};

	/*!
		\brief Equal Area Cylindrical projection
		\ingroup projections
		\tparam LL latlong point type
		\tparam XY xy point type
		\tparam PAR parameter type
		\par Projection characteristics
		 - Cylindrical
		 - Spheroid
		 - Ellipsoid
		 - lat_ts=
		\par Example
		\image html ex_cea.gif
	*/
	template <typename LL, typename XY, typename PAR = parameters>
	struct cea_spheroid : public impl::cea::base_cea_spheroid<LL, XY, PAR>
	{
		inline cea_spheroid(const PAR& par) : impl::cea::base_cea_spheroid<LL, XY, PAR>(par)
		{
			impl::cea::setup_cea(this->m_par, this->m_proj_parm);
		}
	};

	#ifndef DOXYGEN_NO_IMPL
	namespace impl
	{

		// Factory entry(s)
		template <typename LL, typename XY, typename PAR>
		class cea_entry : public impl::factory_entry<LL, XY, PAR>
		{
			public :
				virtual projection<LL, XY>* create_new(const PAR& par) const
				{
					if (par.es)
						return new base_v_fi<cea_ellipsoid<LL, XY, PAR>, LL, XY, PAR>(par);
					else
						return new base_v_fi<cea_spheroid<LL, XY, PAR>, LL, XY, PAR>(par);
				}
		};

		template <typename LL, typename XY, typename PAR>
		inline void cea_init(impl::base_factory<LL, XY, PAR>& factory)
		{
			factory.add_to_factory("cea", new cea_entry<LL, XY, PAR>);
		}

	} // namespace impl
	#endif // doxygen

}

#endif // _PROJECTIONS_CEA_HPP

