#ifndef _PROJECTIONS_NOCOL_HPP
#define _PROJECTIONS_NOCOL_HPP

// Generic Geometry Library - projections (based on PROJ4)
// This file is automatically generated. DO NOT EDIT.

// Copyright Barend Gehrels (1995-2009), Geodan Holding B.V. Amsterdam, the Netherlands.
// Copyright Bruno Lalande (2008-2009)
// Use, modification and distribution is subject to the Boost Software License,
// Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

// This file is converted from PROJ4, http://trac.osgeo.org/proj
// PROJ4 is originally written by Gerald Evenden (then of the USGS)
// PROJ4 is maintained by Frank Warmerdam
// PROJ4 is converted to Geometry Library by Barend Gehrels (Geodan, Amsterdam)

// Original copyright notice:

// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include <geometry/projections/impl/base_static.hpp>
#include <geometry/projections/impl/base_dynamic.hpp>
#include <geometry/projections/impl/projects.hpp>
#include <geometry/projections/impl/factory_entry.hpp>

namespace projection
{
	#ifndef DOXYGEN_NO_IMPL
	namespace impl
	{
		namespace nocol
		{
			static const double EPS = 1e-10;


			// template class, using CRTP to implement forward/inverse
			template <typename LL, typename XY, typename PAR>
			struct base_nocol_spheroid : public base_t_f<base_nocol_spheroid<LL, XY, PAR>, LL, XY, PAR>
			{

				typedef typename base_t_f<base_nocol_spheroid<LL, XY, PAR>, LL, XY, PAR>::LL_T LL_T;
				typedef typename base_t_f<base_nocol_spheroid<LL, XY, PAR>, LL, XY, PAR>::XY_T XY_T;


				inline base_nocol_spheroid(const PAR& par)
					: base_t_f<base_nocol_spheroid<LL, XY, PAR>, LL, XY, PAR>(*this, par) {}

				inline void fwd(LL_T& lp_lon, LL_T& lp_lat, XY_T& xy_x, XY_T& xy_y) const
				{
					if (fabs(lp_lon) < EPS) {
						xy_x = 0;
						xy_y = lp_lat;
					} else if (fabs(lp_lat) < EPS) {
						xy_x = lp_lon;
						xy_y = 0.;
					} else if (fabs(fabs(lp_lon) - HALFPI) < EPS) {
						xy_x = lp_lon * cos(lp_lat);
						xy_y = HALFPI * sin(lp_lat);
					} else if (fabs(fabs(lp_lat) - HALFPI) < EPS) {
						xy_x = 0;
						xy_y = lp_lat;
					} else {
						double tb, c, d, m, n, r2, sp;

						tb = HALFPI / lp_lon - lp_lon / HALFPI;
						c = lp_lat / HALFPI;
						d = (1 - c * c)/((sp = sin(lp_lat)) - c);
						r2 = tb / d;
						r2 *= r2;
						m = (tb * sp / d - 0.5 * tb)/(1. + r2);
						n = (sp / r2 + 0.5 * d)/(1. + 1./r2);
						xy_x = cos(lp_lat);
						xy_x = sqrt(m * m + xy_x * xy_x / (1. + r2));
						xy_x = HALFPI * ( m + (lp_lon < 0. ? -xy_x : xy_x));
						xy_y = sqrt(n * n - (sp * sp / r2 + d * sp - 1.) /
							(1. + 1./r2));
						xy_y = HALFPI * ( n + (lp_lat < 0. ? xy_y : -xy_y ));
					}
				}
			};

			// Nicolosi Globular
			template <typename PAR>
			void setup_nicol(PAR& par)
			{
				par.es = 0.;
				// par.fwd = s_forward;
			}

		} // namespace nocol
	} //namespaces impl
	#endif // doxygen

	/*!
		\brief Nicolosi Globular projection
		\ingroup projections
		\tparam LL latlong point type
		\tparam XY xy point type
		\tparam PAR parameter type
		\par Projection characteristics
		 - Miscellaneous
		 - Spheroid
		 - no inverse
		\par Example
		\image html ex_nicol.gif
	*/
	template <typename LL, typename XY, typename PAR = parameters>
	struct nicol_spheroid : public impl::nocol::base_nocol_spheroid<LL, XY, PAR>
	{
		inline nicol_spheroid(const PAR& par) : impl::nocol::base_nocol_spheroid<LL, XY, PAR>(par)
		{
			impl::nocol::setup_nicol(this->m_par);
		}
	};

	#ifndef DOXYGEN_NO_IMPL
	namespace impl
	{

		// Factory entry(s)
		template <typename LL, typename XY, typename PAR>
		class nicol_entry : public impl::factory_entry<LL, XY, PAR>
		{
			public :
				virtual projection<LL, XY>* create_new(const PAR& par) const
				{
					return new base_v_f<nicol_spheroid<LL, XY, PAR>, LL, XY, PAR>(par);
				}
		};

		template <typename LL, typename XY, typename PAR>
		inline void nocol_init(impl::base_factory<LL, XY, PAR>& factory)
		{
			factory.add_to_factory("nicol", new nicol_entry<LL, XY, PAR>);
		}

	} // namespace impl
	#endif // doxygen

}

#endif // _PROJECTIONS_NOCOL_HPP

