#ifndef _PROJECTIONS_PUTP4P_HPP
#define _PROJECTIONS_PUTP4P_HPP

// Generic Geometry Library - projections (based on PROJ4)
// This file is automatically generated. DO NOT EDIT.

// Copyright Barend Gehrels (1995-2009), Geodan Holding B.V. Amsterdam, the Netherlands.
// Copyright Bruno Lalande (2008-2009)
// Use, modification and distribution is subject to the Boost Software License,
// Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

// This file is converted from PROJ4, http://trac.osgeo.org/proj
// PROJ4 is originally written by Gerald Evenden (then of the USGS)
// PROJ4 is maintained by Frank Warmerdam
// PROJ4 is converted to Geometry Library by Barend Gehrels (Geodan, Amsterdam)

// Original copyright notice:

// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include <geometry/projections/impl/base_static.hpp>
#include <geometry/projections/impl/base_dynamic.hpp>
#include <geometry/projections/impl/projects.hpp>
#include <geometry/projections/impl/factory_entry.hpp>

namespace projection
{
	#ifndef DOXYGEN_NO_IMPL
	namespace impl
	{
		namespace putp4p
		{

			struct par_putp4p
			{
				double C_x, C_y;
			};

			// template class, using CRTP to implement forward/inverse
			template <typename LL, typename XY, typename PAR>
			struct base_putp4p_spheroid : public base_t_fi<base_putp4p_spheroid<LL, XY, PAR>, LL, XY, PAR>
			{

				typedef typename base_t_fi<base_putp4p_spheroid<LL, XY, PAR>, LL, XY, PAR>::LL_T LL_T;
				typedef typename base_t_fi<base_putp4p_spheroid<LL, XY, PAR>, LL, XY, PAR>::XY_T XY_T;

				par_putp4p m_proj_parm;

				inline base_putp4p_spheroid(const PAR& par)
					: base_t_fi<base_putp4p_spheroid<LL, XY, PAR>, LL, XY, PAR>(*this, par) {}

				inline void fwd(LL_T& lp_lon, LL_T& lp_lat, XY_T& xy_x, XY_T& xy_y) const
				{
					lp_lat = aasin(0.883883476 * sin(lp_lat));
					xy_x = this->m_proj_parm.C_x * lp_lon * cos(lp_lat);
					xy_x /= cos(lp_lat *= 0.333333333333333);
					xy_y = this->m_proj_parm.C_y * sin(lp_lat);
				}

				inline void inv(XY_T& xy_x, XY_T& xy_y, LL_T& lp_lon, LL_T& lp_lat) const
				{
					lp_lat = aasin(xy_y / this->m_proj_parm.C_y);
					lp_lon = xy_x * cos(lp_lat) / this->m_proj_parm.C_x;
					lp_lat *= 3.;
					lp_lon /= cos(lp_lat);
					lp_lat = aasin(1.13137085 * sin(lp_lat));
				}
			};

			template <typename PAR>
			void setup(PAR& par, par_putp4p& /*proj_parm*/)
			{
				par.es = 0.;
				// par.inv = s_inverse;
				// par.fwd = s_forward;
			}


			// Putnins P4'
			template <typename PAR>
			void setup_putp4p(PAR& par, par_putp4p& proj_parm)
			{
				proj_parm.C_x = 0.874038744;
				proj_parm.C_y = 3.883251825;
				setup(par, proj_parm);
			}

			// Werenskiold I
			template <typename PAR>
			void setup_weren(PAR& par, par_putp4p& proj_parm)
			{
				proj_parm.C_x = 1.;
				proj_parm.C_y = 4.442882938;
				setup(par, proj_parm);
			}

		} // namespace putp4p
	} //namespaces impl
	#endif // doxygen

	/*!
		\brief Putnins P4' projection
		\ingroup projections
		\tparam LL latlong point type
		\tparam XY xy point type
		\tparam PAR parameter type
		\par Projection characteristics
		 - Pseudocylindrical
		 - Spheroid
		\par Example
		\image html ex_putp4p.gif
	*/
	template <typename LL, typename XY, typename PAR = parameters>
	struct putp4p_spheroid : public impl::putp4p::base_putp4p_spheroid<LL, XY, PAR>
	{
		inline putp4p_spheroid(const PAR& par) : impl::putp4p::base_putp4p_spheroid<LL, XY, PAR>(par)
		{
			impl::putp4p::setup_putp4p(this->m_par, this->m_proj_parm);
		}
	};

	/*!
		\brief Werenskiold I projection
		\ingroup projections
		\tparam LL latlong point type
		\tparam XY xy point type
		\tparam PAR parameter type
		\par Projection characteristics
		 - Pseudocylindrical
		 - Spheroid
		\par Example
		\image html ex_weren.gif
	*/
	template <typename LL, typename XY, typename PAR = parameters>
	struct weren_spheroid : public impl::putp4p::base_putp4p_spheroid<LL, XY, PAR>
	{
		inline weren_spheroid(const PAR& par) : impl::putp4p::base_putp4p_spheroid<LL, XY, PAR>(par)
		{
			impl::putp4p::setup_weren(this->m_par, this->m_proj_parm);
		}
	};

	#ifndef DOXYGEN_NO_IMPL
	namespace impl
	{

		// Factory entry(s)
		template <typename LL, typename XY, typename PAR>
		class putp4p_entry : public impl::factory_entry<LL, XY, PAR>
		{
			public :
				virtual projection<LL, XY>* create_new(const PAR& par) const
				{
					return new base_v_fi<putp4p_spheroid<LL, XY, PAR>, LL, XY, PAR>(par);
				}
		};

		template <typename LL, typename XY, typename PAR>
		class weren_entry : public impl::factory_entry<LL, XY, PAR>
		{
			public :
				virtual projection<LL, XY>* create_new(const PAR& par) const
				{
					return new base_v_fi<weren_spheroid<LL, XY, PAR>, LL, XY, PAR>(par);
				}
		};

		template <typename LL, typename XY, typename PAR>
		inline void putp4p_init(impl::base_factory<LL, XY, PAR>& factory)
		{
			factory.add_to_factory("putp4p", new putp4p_entry<LL, XY, PAR>);
			factory.add_to_factory("weren", new weren_entry<LL, XY, PAR>);
		}

	} // namespace impl
	#endif // doxygen

}

#endif // _PROJECTIONS_PUTP4P_HPP

