#ifndef _PROJECTIONS_STS_HPP
#define _PROJECTIONS_STS_HPP

// Generic Geometry Library - projections (based on PROJ4)
// This file is automatically generated. DO NOT EDIT.

// Copyright Barend Gehrels (1995-2009), Geodan Holding B.V. Amsterdam, the Netherlands.
// Copyright Bruno Lalande (2008-2009)
// Use, modification and distribution is subject to the Boost Software License,
// Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

// This file is converted from PROJ4, http://trac.osgeo.org/proj
// PROJ4 is originally written by Gerald Evenden (then of the USGS)
// PROJ4 is maintained by Frank Warmerdam
// PROJ4 is converted to Geometry Library by Barend Gehrels (Geodan, Amsterdam)

// Original copyright notice:

// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include <geometry/projections/impl/base_static.hpp>
#include <geometry/projections/impl/base_dynamic.hpp>
#include <geometry/projections/impl/projects.hpp>
#include <geometry/projections/impl/factory_entry.hpp>

namespace projection
{
	#ifndef DOXYGEN_NO_IMPL
	namespace impl
	{
		namespace sts
		{

			struct par_sts
			{
				double C_x, C_y, C_p;
				int tan_mode;
			};

			// template class, using CRTP to implement forward/inverse
			template <typename LL, typename XY, typename PAR>
			struct base_sts_spheroid : public base_t_fi<base_sts_spheroid<LL, XY, PAR>, LL, XY, PAR>
			{

				typedef typename base_t_fi<base_sts_spheroid<LL, XY, PAR>, LL, XY, PAR>::LL_T LL_T;
				typedef typename base_t_fi<base_sts_spheroid<LL, XY, PAR>, LL, XY, PAR>::XY_T XY_T;

				par_sts m_proj_parm;

				inline base_sts_spheroid(const PAR& par)
					: base_t_fi<base_sts_spheroid<LL, XY, PAR>, LL, XY, PAR>(*this, par) {}

				inline void fwd(LL_T& lp_lon, LL_T& lp_lat, XY_T& xy_x, XY_T& xy_y) const
				{
					double c;

					xy_x = this->m_proj_parm.C_x * lp_lon * cos(lp_lat);
					xy_y = this->m_proj_parm.C_y;
					lp_lat *= this->m_proj_parm.C_p;
					c = cos(lp_lat);
					if (this->m_proj_parm.tan_mode) {
						xy_x *= c * c;
						xy_y *= tan(lp_lat);
					} else {
						xy_x /= c;
						xy_y *= sin(lp_lat);
					}
				}

				inline void inv(XY_T& xy_x, XY_T& xy_y, LL_T& lp_lon, LL_T& lp_lat) const
				{
					double c;

					xy_y /= this->m_proj_parm.C_y;
					c = cos(lp_lat = this->m_proj_parm.tan_mode ? atan(xy_y) : aasin(xy_y));
					lp_lat /= this->m_proj_parm.C_p;
					lp_lon = xy_x / (this->m_proj_parm.C_x * cos(lp_lat /= this->m_proj_parm.C_p));
					if (this->m_proj_parm.tan_mode)
						lp_lon /= c * c;
					else
						lp_lon *= c;
				}
			};

			template <typename PAR>
			void setup(PAR& par, par_sts& proj_parm, double p, double q, int mode)
			{
				par.es = 0.;
				// par.inv = s_inverse;
				// par.fwd = s_forward;
				proj_parm.C_x = q / p;
				proj_parm.C_y = p;
				proj_parm.C_p = 1/ q;
				proj_parm.tan_mode = mode;
			}


			// Kavraisky V
			template <typename PAR>
			void setup_kav5(PAR& par, par_sts& proj_parm)
			{
				setup(par, proj_parm, 1.50488, 1.35439, 0);
			}

			// Quartic Authalic
			template <typename PAR>
			void setup_qua_aut(PAR& par, par_sts& proj_parm)
			{
				setup(par, proj_parm, 2., 2., 0);
			}

			// McBryde-Thomas Flat-Polar Sine (No. 1)
			template <typename PAR>
			void setup_mbt_s(PAR& par, par_sts& proj_parm)
			{
				setup(par, proj_parm, 1.48875, 1.36509, 0);
			}

			// Foucaut
			template <typename PAR>
			void setup_fouc(PAR& par, par_sts& proj_parm)
			{
				setup(par, proj_parm, 2., 2., 1);
			}

		} // namespace sts
	} //namespaces impl
	#endif // doxygen

	/*!
		\brief Kavraisky V projection
		\ingroup projections
		\tparam LL latlong point type
		\tparam XY xy point type
		\tparam PAR parameter type
		\par Projection characteristics
		 - Pseudocylindrical
		 - Spheroid
		\par Example
		\image html ex_kav5.gif
	*/
	template <typename LL, typename XY, typename PAR = parameters>
	struct kav5_spheroid : public impl::sts::base_sts_spheroid<LL, XY, PAR>
	{
		inline kav5_spheroid(const PAR& par) : impl::sts::base_sts_spheroid<LL, XY, PAR>(par)
		{
			impl::sts::setup_kav5(this->m_par, this->m_proj_parm);
		}
	};

	/*!
		\brief Quartic Authalic projection
		\ingroup projections
		\tparam LL latlong point type
		\tparam XY xy point type
		\tparam PAR parameter type
		\par Projection characteristics
		 - Pseudocylindrical
		 - Spheroid
		\par Example
		\image html ex_qua_aut.gif
	*/
	template <typename LL, typename XY, typename PAR = parameters>
	struct qua_aut_spheroid : public impl::sts::base_sts_spheroid<LL, XY, PAR>
	{
		inline qua_aut_spheroid(const PAR& par) : impl::sts::base_sts_spheroid<LL, XY, PAR>(par)
		{
			impl::sts::setup_qua_aut(this->m_par, this->m_proj_parm);
		}
	};

	/*!
		\brief McBryde-Thomas Flat-Polar Sine (No. 1) projection
		\ingroup projections
		\tparam LL latlong point type
		\tparam XY xy point type
		\tparam PAR parameter type
		\par Projection characteristics
		 - Pseudocylindrical
		 - Spheroid
		\par Example
		\image html ex_mbt_s.gif
	*/
	template <typename LL, typename XY, typename PAR = parameters>
	struct mbt_s_spheroid : public impl::sts::base_sts_spheroid<LL, XY, PAR>
	{
		inline mbt_s_spheroid(const PAR& par) : impl::sts::base_sts_spheroid<LL, XY, PAR>(par)
		{
			impl::sts::setup_mbt_s(this->m_par, this->m_proj_parm);
		}
	};

	/*!
		\brief Foucaut projection
		\ingroup projections
		\tparam LL latlong point type
		\tparam XY xy point type
		\tparam PAR parameter type
		\par Projection characteristics
		 - Pseudocylindrical
		 - Spheroid
		\par Example
		\image html ex_fouc.gif
	*/
	template <typename LL, typename XY, typename PAR = parameters>
	struct fouc_spheroid : public impl::sts::base_sts_spheroid<LL, XY, PAR>
	{
		inline fouc_spheroid(const PAR& par) : impl::sts::base_sts_spheroid<LL, XY, PAR>(par)
		{
			impl::sts::setup_fouc(this->m_par, this->m_proj_parm);
		}
	};

	#ifndef DOXYGEN_NO_IMPL
	namespace impl
	{

		// Factory entry(s)
		template <typename LL, typename XY, typename PAR>
		class kav5_entry : public impl::factory_entry<LL, XY, PAR>
		{
			public :
				virtual projection<LL, XY>* create_new(const PAR& par) const
				{
					return new base_v_fi<kav5_spheroid<LL, XY, PAR>, LL, XY, PAR>(par);
				}
		};

		template <typename LL, typename XY, typename PAR>
		class qua_aut_entry : public impl::factory_entry<LL, XY, PAR>
		{
			public :
				virtual projection<LL, XY>* create_new(const PAR& par) const
				{
					return new base_v_fi<qua_aut_spheroid<LL, XY, PAR>, LL, XY, PAR>(par);
				}
		};

		template <typename LL, typename XY, typename PAR>
		class mbt_s_entry : public impl::factory_entry<LL, XY, PAR>
		{
			public :
				virtual projection<LL, XY>* create_new(const PAR& par) const
				{
					return new base_v_fi<mbt_s_spheroid<LL, XY, PAR>, LL, XY, PAR>(par);
				}
		};

		template <typename LL, typename XY, typename PAR>
		class fouc_entry : public impl::factory_entry<LL, XY, PAR>
		{
			public :
				virtual projection<LL, XY>* create_new(const PAR& par) const
				{
					return new base_v_fi<fouc_spheroid<LL, XY, PAR>, LL, XY, PAR>(par);
				}
		};

		template <typename LL, typename XY, typename PAR>
		inline void sts_init(impl::base_factory<LL, XY, PAR>& factory)
		{
			factory.add_to_factory("kav5", new kav5_entry<LL, XY, PAR>);
			factory.add_to_factory("qua_aut", new qua_aut_entry<LL, XY, PAR>);
			factory.add_to_factory("mbt_s", new mbt_s_entry<LL, XY, PAR>);
			factory.add_to_factory("fouc", new fouc_entry<LL, XY, PAR>);
		}

	} // namespace impl
	#endif // doxygen

}

#endif // _PROJECTIONS_STS_HPP

