#ifndef _PROJECTIONS_TCEA_HPP
#define _PROJECTIONS_TCEA_HPP

// Generic Geometry Library - projections (based on PROJ4)
// This file is automatically generated. DO NOT EDIT.

// Copyright Barend Gehrels (1995-2009), Geodan Holding B.V. Amsterdam, the Netherlands.
// Copyright Bruno Lalande (2008-2009)
// Use, modification and distribution is subject to the Boost Software License,
// Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

// This file is converted from PROJ4, http://trac.osgeo.org/proj
// PROJ4 is originally written by Gerald Evenden (then of the USGS)
// PROJ4 is maintained by Frank Warmerdam
// PROJ4 is converted to Geometry Library by Barend Gehrels (Geodan, Amsterdam)

// Original copyright notice:

// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include <geometry/projections/impl/base_static.hpp>
#include <geometry/projections/impl/base_dynamic.hpp>
#include <geometry/projections/impl/projects.hpp>
#include <geometry/projections/impl/factory_entry.hpp>

namespace projection
{
	#ifndef DOXYGEN_NO_IMPL
	namespace impl
	{
		namespace tcea
		{

			struct par_tcea
			{
				double rk0;
			};

			// template class, using CRTP to implement forward/inverse
			template <typename LL, typename XY, typename PAR>
			struct base_tcea_spheroid : public base_t_fi<base_tcea_spheroid<LL, XY, PAR>, LL, XY, PAR>
			{

				typedef typename base_t_fi<base_tcea_spheroid<LL, XY, PAR>, LL, XY, PAR>::LL_T LL_T;
				typedef typename base_t_fi<base_tcea_spheroid<LL, XY, PAR>, LL, XY, PAR>::XY_T XY_T;

				par_tcea m_proj_parm;

				inline base_tcea_spheroid(const PAR& par)
					: base_t_fi<base_tcea_spheroid<LL, XY, PAR>, LL, XY, PAR>(*this, par) {}

				inline void fwd(LL_T& lp_lon, LL_T& lp_lat, XY_T& xy_x, XY_T& xy_y) const
				{
					xy_x = this->m_proj_parm.rk0 * cos(lp_lat) * sin(lp_lon);
					xy_y = this->m_par.k0 * (atan2(tan(lp_lat), cos(lp_lon)) - this->m_par.phi0);
				}

				inline void inv(XY_T& xy_x, XY_T& xy_y, LL_T& lp_lon, LL_T& lp_lat) const
				{
					double t;

					xy_y = xy_y * this->m_proj_parm.rk0 + this->m_par.phi0;
					xy_x *= this->m_par.k0;
					t = sqrt(1. - xy_x * xy_x);
					lp_lat = asin(t * sin(xy_y));
					lp_lon = atan2(xy_x, t * cos(xy_y));
				}
			};

			// Transverse Cylindrical Equal Area
			template <typename PAR>
			void setup_tcea(PAR& par, par_tcea& proj_parm)
			{
				proj_parm.rk0 = 1 / par.k0;
				// par.inv = s_inverse;
				// par.fwd = s_forward;
				par.es = 0.;
			}

		} // namespace tcea
	} //namespaces impl
	#endif // doxygen

	/*!
		\brief Transverse Cylindrical Equal Area projection
		\ingroup projections
		\tparam LL latlong point type
		\tparam XY xy point type
		\tparam PAR parameter type
		\par Projection characteristics
		 - Cylindrical
		 - Spheroid
		\par Example
		\image html ex_tcea.gif
	*/
	template <typename LL, typename XY, typename PAR = parameters>
	struct tcea_spheroid : public impl::tcea::base_tcea_spheroid<LL, XY, PAR>
	{
		inline tcea_spheroid(const PAR& par) : impl::tcea::base_tcea_spheroid<LL, XY, PAR>(par)
		{
			impl::tcea::setup_tcea(this->m_par, this->m_proj_parm);
		}
	};

	#ifndef DOXYGEN_NO_IMPL
	namespace impl
	{

		// Factory entry(s)
		template <typename LL, typename XY, typename PAR>
		class tcea_entry : public impl::factory_entry<LL, XY, PAR>
		{
			public :
				virtual projection<LL, XY>* create_new(const PAR& par) const
				{
					return new base_v_fi<tcea_spheroid<LL, XY, PAR>, LL, XY, PAR>(par);
				}
		};

		template <typename LL, typename XY, typename PAR>
		inline void tcea_init(impl::base_factory<LL, XY, PAR>& factory)
		{
			factory.add_to_factory("tcea", new tcea_entry<LL, XY, PAR>);
		}

	} // namespace impl
	#endif // doxygen

}

#endif // _PROJECTIONS_TCEA_HPP

