#ifndef _PROJECTIONS_URM5_HPP
#define _PROJECTIONS_URM5_HPP

// Generic Geometry Library - projections (based on PROJ4)
// This file is automatically generated. DO NOT EDIT.

// Copyright Barend Gehrels (1995-2009), Geodan Holding B.V. Amsterdam, the Netherlands.
// Copyright Bruno Lalande (2008-2009)
// Use, modification and distribution is subject to the Boost Software License,
// Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

// This file is converted from PROJ4, http://trac.osgeo.org/proj
// PROJ4 is originally written by Gerald Evenden (then of the USGS)
// PROJ4 is maintained by Frank Warmerdam
// PROJ4 is converted to Geometry Library by Barend Gehrels (Geodan, Amsterdam)

// Original copyright notice:

// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include <geometry/projections/impl/base_static.hpp>
#include <geometry/projections/impl/base_dynamic.hpp>
#include <geometry/projections/impl/projects.hpp>
#include <geometry/projections/impl/factory_entry.hpp>

namespace projection
{
	#ifndef DOXYGEN_NO_IMPL
	namespace impl
	{
		namespace urm5
		{

			struct par_urm5
			{
				double m, rmn, q3, n;
			};

			// template class, using CRTP to implement forward/inverse
			template <typename LL, typename XY, typename PAR>
			struct base_urm5_spheroid : public base_t_f<base_urm5_spheroid<LL, XY, PAR>, LL, XY, PAR>
			{

				typedef typename base_t_f<base_urm5_spheroid<LL, XY, PAR>, LL, XY, PAR>::LL_T LL_T;
				typedef typename base_t_f<base_urm5_spheroid<LL, XY, PAR>, LL, XY, PAR>::XY_T XY_T;

				par_urm5 m_proj_parm;

				inline base_urm5_spheroid(const PAR& par)
					: base_t_f<base_urm5_spheroid<LL, XY, PAR>, LL, XY, PAR>(*this, par) {}

				inline void fwd(LL_T& lp_lon, LL_T& lp_lat, XY_T& xy_x, XY_T& xy_y) const
				{
					double t;

					t = lp_lat = aasin(this->m_proj_parm.n * sin(lp_lat));
					xy_x = this->m_proj_parm.m * lp_lon * cos(lp_lat);
					t *= t;
					xy_y = lp_lat * (1. + t * this->m_proj_parm.q3) * this->m_proj_parm.rmn;
				}
			};

			// Urmaev V
			template <typename PAR>
			void setup_urm5(PAR& par, par_urm5& proj_parm)
			{
				double alpha, t;
				proj_parm.n = pj_param(par.params, "dn").f;
				proj_parm.q3 = pj_param(par.params, "dq").f / 3.;
				alpha = pj_param(par.params, "ralpha").f;
				t = proj_parm.n * sin(alpha);
				proj_parm.m = cos(alpha) / sqrt(1. - t * t);
				proj_parm.rmn = 1. / (proj_parm.m * proj_parm.n);
				par.es = 0.;
				// par.inv = 0;
				// par.fwd = s_forward;
			}

		} // namespace urm5
	} //namespaces impl
	#endif // doxygen

	/*!
		\brief Urmaev V projection
		\ingroup projections
		\tparam LL latlong point type
		\tparam XY xy point type
		\tparam PAR parameter type
		\par Projection characteristics
		 - Pseudocylindrical
		 - Spheroid
		 - n= q= alphi=
		\par Example
		\image html ex_urm5.gif
	*/
	template <typename LL, typename XY, typename PAR = parameters>
	struct urm5_spheroid : public impl::urm5::base_urm5_spheroid<LL, XY, PAR>
	{
		inline urm5_spheroid(const PAR& par) : impl::urm5::base_urm5_spheroid<LL, XY, PAR>(par)
		{
			impl::urm5::setup_urm5(this->m_par, this->m_proj_parm);
		}
	};

	#ifndef DOXYGEN_NO_IMPL
	namespace impl
	{

		// Factory entry(s)
		template <typename LL, typename XY, typename PAR>
		class urm5_entry : public impl::factory_entry<LL, XY, PAR>
		{
			public :
				virtual projection<LL, XY>* create_new(const PAR& par) const
				{
					return new base_v_f<urm5_spheroid<LL, XY, PAR>, LL, XY, PAR>(par);
				}
		};

		template <typename LL, typename XY, typename PAR>
		inline void urm5_init(impl::base_factory<LL, XY, PAR>& factory)
		{
			factory.add_to_factory("urm5", new urm5_entry<LL, XY, PAR>);
		}

	} // namespace impl
	#endif // doxygen

}

#endif // _PROJECTIONS_URM5_HPP

