.TH MERKAARTOR 1
.SH NAME
Merkaartor \- map editor for OpenStreetMap.org
.SH SYNOPSIS
.B merkaartor
.SH DESCRIPTION
Merkaartor is a map editor for OpenStreetMap.org, the free editable map of the
whole world.
.SH OPTIONS
None.
.SH "SEE ALSO"
viking(1).
.SH AUTHORS
Bart Vanhauwaert,
Elrond,
Oliver Heesakkers,
Patric Cameron,
Geoff Richards,
Raphael Studer,
Matt Williams,
Chris Browet,
Daniel van Gerpen.
